In [1]:
from modules.constellation import SatelliteConstellation, PointingStrategy
import numpy as np
import matplotlib.pyplot as plt

In [2]:


constellation = SatelliteConstellation(pointing_offset_deg=25)

constellation.add_satellite_from_tle(name = 'Spirit',
                                     line1 = '1 58468U 23185G   25058.90294474  .00035172  00000+0  11098-2 0  9997',
                                     line2 = '2 58468  97.3898 128.8229 0010982 203.8018 256.4447 15.32718055 69105'
                                    )

# Until we have TLE's for HERMES, just initialise them as spirit-like orbits with a different raan,
# equally spaced around their orbital plane (through the raan)
for hermes_idx in range(1,7):

    arg_perigee = np.round((hermes_idx - 1) * 60, 4)
    raan = 110.0000 # close to Spirit's plane, but not quite

    constellation.add_satellite_from_tle(name = f'HERMES_{hermes_idx}',
                                        line1 = '1 58468U 23185G   25058.90294474  .00035172  00000+0  11098-2 0  9997',
                                        line2 = f'2 58468  97.3898 {raan} 0010982 {arg_perigee} 256.4447 15.32718055 69105'
                                        )

In [ ]:
'''
Basic Usage
'''

# You need to set the time using a datetime object, which we
# can call through the SatelliteConstellation class

current_time = constellation.get_current_time()

constellation.set_time(time = current_time)

print('The current UTC time is:', constellation.time.tt_strftime() )
# .tt_strftime() just converts the time object into human readable format

###

# We can also generate random times up to a few weeks into
# the future (its unwise to go further than this because
# TLE accuracy gets quite bad after about 2 weeks).
#  - we will probably using this random feature the most
#    when generating GRB times for MCMC

constellation.set_time(random = True)

print('Randomly generated time:', constellation.time.tt_strftime() )

# Now that the time is set, we can get the constellation's cartesian
# position and pointing vectors with two easy functions

positions = constellation.get_xyz()

print('\n> Satellite positions at', constellation.time.tt_strftime(), ':')
print(positions)

pointings, pointing_group_centres = constellation.get_pointing_radec()

print('\n> Satellite pointings at', constellation.time.tt_strftime(), ':')
print(pointings)

# Pointings are formatted as ra, dec, where:
#       0 < ra < 2 * pi
#       -pi < dec < pi


The current UTC time is: 2025-03-03 05:00:09 TT
Randomly generated time: 2025-03-13 10:30:32 TT

> Satellite positions at 2025-03-13 10:30:32 TT :
[[ 2754.88287679 -4960.31463159 -3834.89119757]
 [ 1590.20800427 -5151.8361138  -3135.33495415]
 [ -893.5254765  -2884.26124721 -6063.24257197]
 [-3707.56302894  3117.84356222 -4732.19373128]
 [-2818.46690473  6005.10095772  1324.4088828 ]
 [  892.43948213  2876.71829244  6050.40678116]
 [ 3708.20474231 -3134.98268055  4710.53727451]]

> Satellite pointings at 2025-03-13 10:30:32 TT :
[[ 1.90939262  0.        ]
 [ 1.4730603   0.        ]
 [ 1.69122646 -0.21816616]
 [ 5.01271911 -0.1799    ]
 [ 4.65291911 -0.1799    ]
 [ 4.83281911  0.1799    ]
 [ 1.69122646  0.21816616]]
